title: CS 3100 
description: >
  Data Structures and Algorithms 2 
copyright: Tom Horton and John Hott
baseurl: "/"
email: "jh2jf@virginia.edu"
theme: just-the-docs
search:
    button: true
callouts:
    warning:
        title: Warning
        color: red
    notice:
        title: Note
        color: purple
    aside:
        title: Aside
        color: blue
    hint:
        title: Hint
        color: green
